[versions]
agp = "8.13.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"

#test
mockk = "1.14.7"
coroutinTest = "1.7.3"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

#compose
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.12.00"
appcompat = "1.7.1"
material = "1.13.0"
jetbrainsKotlinJvm = "2.2.21"
navigationCompose = "2.9.6"


kotlinxSerializationJson = "1.9.0"
materialIconsExtended = "1.7.8"
coreSplashscreen = "1.0.1"

# java.LocalTime
desugar = "2.0.4"

#coroutine
coroutines = "1.10.2"
# ksp
ksp = "2.2.0-2.0.2"
#Room
room = "2.7.2"

# Hilt Core
hilt = "2.57"
# Hilt Navigation
hiltNavigationCompose = "1.2.0"

#Firestore
firebaseBom = "34.6.0"
googleGmsServices = "4.4.4"

#kotlin-seriaization
kotlinxSerialization = "1.9.0"


#REST
retrofit = "3.0.0"
moshi = "1.15.2"
loggingInterceptor = "4.12.0"
mockwebserver = "4.12.0"
playServicesAnalyticsImpl = "18.2.0"
javaxInject = "1"
foundationLayout = "1.10.0"
foundation = "1.10.1"

#coil
coilCompose = "3.3.0"
coilNetworkOkhttp = "3.3.0"

#Log
timber = "5.0.1"

#on-deivce
camerax  = "1.5.2"
camerax-compose = "1.5.0"

#Accompanist
accompanist-permissions = "0.37.3"

#AI
poseDetection = "18.0.0-beta5"
runtime = "1.10.3"

[libraries]
# Android Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }

# Compose BOM
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIconsExtended" }

# Coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test",version.ref="coroutinTest" }

# Serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# Network
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "mockwebserver" }

#Firestore
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }

# Coil
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coilCompose" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coilNetworkOkhttp" }

#camerax
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camerax" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camerax" }
camera-compose = { group = "androidx.camera", name = "camera-compose", version.ref = "camerax-compose" }

# ML Kit
pose-detection = { group = "com.google.mlkit", name = "pose-detection", version.ref = "poseDetection" }
pose-detection-common = { group = "com.google.mlkit", name = "pose-detection-common", version.ref = "poseDetection" }

# Logging
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# Desugar
desugar-jdk = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }

# Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }

javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxInject" }

accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist-permissions" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin"}

hilt-gradle = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsServices" }


[bundles]

android-core = [
    "androidx-core-ktx",
    "androidx-lifecycle-runtime-ktx",
    "androidx-core-splashscreen"
]

compose = [
    "androidx-activity-compose",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-material3",
    "androidx-compose-ui-tooling-preview",
    "androidx-navigation-compose",
    "androidx-compose-material-icons-extended"
]

hilt = [
    "hilt-android",
    "hilt-navigation-compose"
]

room = [
    "androidx-room-runtime",
    "androidx-room-ktx"
]

network = [
    "retrofit-core",
    "retrofit-converter-moshi",
    "moshi-kotlin",
    "logging-interceptor"
]

network-test = [
    "mockwebserver"
]

firebase = [
    "firebase-firestore",
    "firebase-auth"
]

coil = [
    "coil-compose",
    "coil-network-okhttp"
]

camerax = [
    "camera-core",
    "camera-camera2",
    "camera-lifecycle",
    "camera-view",
    "camera-compose"
]

mlkit-pose = [
    "pose-detection",
    "pose-detection-common"
]

test-jvm = [
    "junit",
    "mockk",
    "coroutines-test"
]

test-android = [
    "androidx-junit",
    "androidx-espresso-core",
    "androidx-compose-ui-test-junit4",
    "mockk-android"
]